### ISSUE TITLE
Request: a subcommand to clean the temp projects

### ISSUE THREAD

**Issue by amanjeev** [yozhgoor/cargo-temp#63]
## Current state

I cannot find a way to safely clean the project directory.

## Feature request

A flag to remove projects that are safe to remove like the ones with `TO_DELETE` file.

Perhaps a second `--force` like flag that removes all projects, no matter whether they have the `TO_DELETE` file or not.

**Comment by yozhgoor** [comment]
Note that you can't logically have projects with a `TO_DELETE` in your project directory. When you exit the shell, the project is preserved only if the `TO_DELETE` doesn't exists. So this project become a "normal" Rust project with a `tmp-...` name (or `wk-...`).
You can also change the temporary projects directory in your config, It would not be easy to ensure that I can delete projects if the user change the projects directory as the directory where all their projects are stored (temporary projects or not).

For me the best solution here is to open your temporary projects directory (you can check the `temporary_project_dir` key in your config file if you don't remember) and manually delete the projects using your file system manager or terminal.

**Comment by yozhgoor** [comment]
I'm going to add a prompt to confirm that you want to delete the project (only when the `TO_DELETE` file still exists when exiting the shell. I can maybe add others options to this prompt to delete all the projects based on the prefix but I don't think it would be a good idea since `cargo temp` focus on the temporary project currently in use instead of all the temporary projects created.

**Comment by amanjeev** [comment]
Many thanks! This is a good explainer and I now understand the philosophy more. Thank you!

**Comment by cecton** [comment]
I fear we are missing something here....

cargo-temp already cleans-up the projects automatically. I assume you found cases where this doesn't happen?

**Comment by amanjeev** [comment]
I just created a new temp proj and then `cd`'d out of it but I still see it. 

```
aj in ⟪irony⟫ ~/.cache/cargo-temp/tmp-VXKFR3  on  main [?] is 📦 v0.1.0 via 🦀 v1.63.0 
at 10:52:23  ❤  cd ..
aj in ⟪irony⟫ ~/.cache/cargo-temp  
at 10:52:25  ❤  ll
total 48K
drwxrwxr-x 4 aj aj 4.0K Jul 13 13:14 tmp-cWjE2W/
drwxrwxr-x 5 aj aj 4.0K Aug 29 11:21 tmp-DyJ0yy/
drwxrwxr-x 4 aj aj 4.0K Aug 29 13:46 tmp-e23w85/
drwxrwxr-x 5 aj aj 4.0K Aug  1 18:15 tmp-EH31n4/
drwxrwxr-x 4 aj aj 4.0K Aug 29 13:40 tmp-EUJxfl/
drwxrwxr-x 5 aj aj 4.0K Aug 11 16:06 tmp-kdrFhE/
drwxrwxr-x 5 aj aj 4.0K Aug 23 14:00 tmp-oAjXFx/
drwxrwxr-x 4 aj aj 4.0K Aug  4 11:05 tmp-tXIy74/
drwxrwxr-x 6 aj aj 4.0K Jul 21 15:04 tmp-U0lHj9/
drwxrwxr-x 4 aj aj 4.0K Aug 30 10:52 tmp-VXKFR3/
drwxrwxr-x 5 aj aj 4.0K Jul 24 16:29 tmp-WZtNYq/
```
But I realize that I need to Ctrl+D the shell for it to be cleaned up. This is what I learned lol (not reading the manuals).

**Comment by cecton** [comment]
Maybe a welcome message could be printed before entering the shell. Who reads manuals anyway lol

**Comment by amanjeev** [comment]
I second a welcome message.

**Comment by yozhgoor** [comment]
So, we have some ideas there:

* A command like `cargo-temp prune` to delete project in the `temporary_project_dir` if they still have a `TO_DELETE` file.
* A welcome message to indicate where the project have been created and how to exit the temporary project.

**Comment by cecton** [comment]
I'd suggest you forget about the prune command because it can be difficult to implement properly and there are no more requests for it. (@amanjeev correct me if I'm wrong)

The welcome message is supported by 2 people already and is easy to implement. Sometimes the stupid solution is the best because it avoids unnecessary maintenance cost. (Sometimes we still do an overengineered solution for the fun and that is fine really, don't worry, don't be too serious.)

@yozhgoor also please note that you failed to see the peculiarity of the feature request and you answered in a way that didn't help to clarify things. I mean you're polite and nice and everything (which is AWESOME seriously) but you also need to make sure you fully understand what people ask in the first place. As a result, you could have ended up developing an unnecessary feature.

As an advice I would say it is important to have the right balance between: understanding the issue enough & not being inquisitive. Questioning too hard any feature or any request is terrible but not questioning enough is not helping.

**Comment by amanjeev** [comment]
I am fine with only the message. Honestly, I open issues mostly to see if they are feasible. You are the maintainers so you do have the last word. I appreciate this project and yall a lot! 💟
